specVersion: v0.1.0
package:
  name: {{NAME}}
  version: {{VERSION}}

imports:
  sql: https://github.com/streamingfast/substreams-sink-sql/releases/download/protodefs-v1.0.7/substreams-sink-sql-protodefs-v1.0.7.spkg
  database_change: https://github.com/streamingfast/substreams-sink-database-changes/releases/download/v1.3.0/substreams-sink-database-changes-v1.3.0.spkg

binaries:
  default:
    type: wasm/rust-v1
    file: ../../target/wasm32-unknown-unknown/release/optimus_events.wasm

modules:
  - name: db_out
    kind: map
    inputs:
      - source: sf.ethereum.type.v2.Block
    output:
      type: proto:sf.substreams.sink.database.v1.DatabaseChanges

sink:
  module: db_out
  type: sf.substreams.sink.sql.v1.Service
  config:
    schema: ./schema.sql
    engine: clickhouse

network: {{NETWORK}}